name: Robot Framework Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install webdriver-manager

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run Robot Tests
      run: |
        python -m robot testscases/login_features.robot

    - name: Upload Robot Reports
      uses: actions/upload-artifact@v4
      with:
        name: robot-reports
        path: |
          report.html
          log.html
          output.xml